# Generated by Django 4.1 on 2022-08-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_project_modified_by_alter_project_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("Art", "Art"),
                    ("Culture", "Culture"),
                    ("Creativity", "Creativity"),
                    ("Education", "Education"),
                    ("Film", "Film"),
                    ("Food & Crafts", "Food & Crafts"),
                    ("Game", "Game"),
                    ("Music", "Music"),
                    ("Publishing", "Publishing"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_image",
            field=models.ImageField(default="static/1.jpg", upload_to="static/"),
        ),
    ]
