# Generated by Django 4.1 on 2022-08-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_project_category_project_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_image",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
